# Generated by Django 4.2 on 2024-06-17 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='conplete',
            new_name='complete',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
